export const clueMap = [
  [0, 1],
  [0, 4],
  [0, 8],
  [0, 11],
  [1, 8],
  [1, 12],
  [2, 1],
  [2, 3],
  [2, 11],
  [2, 14],
  [3, 0],
  [3, 7],
  [3, 10],
  [4, 6],
  [4, 9],
  [5, 1],
  [5, 2],
  [5, 5],
  [5, 12],
  [5, 13],
  [6, 0],
  [6, 9],
  [6, 12],
  [7, 1],
  [7, 8],
  [7, 12],
  [8, 3],
  [10, 4],
  [10, 8],
  [10, 11],
  [11, 0],
  [12, 0],
  [12, 2],
  [12, 3],
  [12, 5],
  [12, 11],
  [12, 13],
  [13, 2],
  [13, 5],
  [13, 6],
  [13, 9],
  [14, 0],
]

export const acrossClues = [
  [1, 'Title of the poster that made Noah Nevens a celebrity among the prefrosh', 0],
  [5, 'Like Argon or Helium', 4],
  [8, 'Alternative for a box at the end of a proof', 7],
  [9, 'Grutoring but for non-CS classes', 8],
  [11, 'Question 11', 10],
  [12, "A Mudder's favorite dessert?", 11],
  [
    13,
    'Circuit device, shaped like a triangle, that Dan once drew pretty well after spinning around 10 times',
    12,
  ],
  [14, 'Danger', 13],
  [16, 'Like Red in Among Us, say', 15],
  [18, 'Something made in a press', 17],
  [19, 'Thing said while clapping your hands together and pointing at someone', 18],
  [21, 'Healy of The 1975', 20],
  [22, 'Radiation with types A, B, and C', 21],
  [23, 'Someone who helps organize Room Draw', 22],
  [24, 'Customizable Nintendo avatar', 23],
  [
    26,
    'What a PM might feel when reading the Slack message "We\'re presenting to Wloka right, either way no"',
    25,
  ],
  [27, 'MIA, or Dan on the drums', 26],
  [28, 'First name of the Mandalorian', 27],
  [29, 'Color with RGB value (224, 176, 255)', 28],
  [32, 'Popular brand for the food that Dan commonly steals from the CS kitchen', 31],
  [36, 'Card that the T-Mobile people fucked over Anshul with like 3 times that one day', 35],
  [38, 'Prefix for sexual, cycle, or corn', 36],
  [39, 'Cheating section in the grocery store', 38],
  [42, 'Type of theory taught by Prof Wright', 41],
]

export const downClues = [
  [2, 'The H in HSV but plural', 1],
  [3, 'Type of un-rolled sushi', 2],
  [4, '"It\'s a _____!" -Admiral Ackbar', 3],
  [6, 'Kermit sips this', 5],
  [
    7,
    'A fine, filmy substance consisting of cobwebs spun by small spiders, seen especially in autumn',
    6,
  ],
  [8, 'Taylor Swift song on Midnights that "needs a huge explicit disclaimer"', 7],
  [10, 'Race-car feature also found on Toby (rip in peace little guy)', 9],
  [12, 'You hear this click in Taylor Swift\'s "Blank Space"', 11],
  [13, "Middle name on Eric's fake ID, or one of the Picks", 12],
  [14, 'Albany main in Smash', 13],
  [15, 'Dog in Japanese', 14],
  [17, 'Unfortunate acronym for a nearby school', 16],
  [19, "Middle name on Daniela's real ID, almost", 18],
  [20, 'Rowing implement', 19],
  [25, 'Type of cyst with hair and teeth', 24],
  [30, 'Word that Khaya Kingston definitely pronounces wrong', 29],
  [31, 'Drink whose Hoch machine could be used to produce purple, in theory', 30],
  [33, 'IMHO', 32],
  [34, 'King Richard ____', 33],
  [35, "I <3 ____ (on Eli's shirt)", 34],
  [37, 'Chairman after whom a card game may be named', 36],
  [40, 'Type of circuit with a resistor and an inductor', 39],
  [41, 'Pixar film with the track "Married Life"', 40],
]

export const crosswordEncoding = [
  '-ONTHERUN--T---',
  '----U---INERT--',
  '-G-QED--G--AE-S',
  'BONUS--PI-OPAMP',
  '-S-E--PERIL---O',
  '-SUS-PANINI-BOI',
  'MATTY-L--UV-RAL',
  '-MII--U-D-E-IRE',
  '-E-OFFTHEGRID-R',
  '-R-N--E-R---G--',
  '----DIN-MAUVE--',
  'I-----A-O--A---',
  'CUTIES--I--SIM-',
  'E-BI-PRODUCE-A-',
  'ETHICAL--P---O-',
].join('')

export const crosswordTemplate = [
  '-________--_---',
  '----_---_____--',
  '-_-___--_--__-_',
  '_____--__-_____',
  '-_-_--_____---_',
  '-___-______-___',
  '_____-_--__-___',
  '-___--_-_-_-___',
  '-_-__________-_',
  '-_-_--_-_---_--',
  '----___-_____--',
  '_-----_-_--_---',
  '______--_--___-',
  '_-__-_______-_-',
  '_______--_---_-',
]

export const solution = [
  [1, 8],
  [7, 1],
  [8, 5],
  [8, 14],
  [14, 5],
]
